<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\AgentsController;
/*
|--------------------------------------------------------------------------
| Core App Routes
|--------------------------------------------------------------------------
*/
Route::get('/', [ReportController::class, 'dashboard'])->name('dashboard');
Route::get('/dashboard', [ReportController::class, 'dashboard'])->name('home');
Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
Route::get('/reports/export/{format}', [ReportController::class, 'export'])->name('reports.export');
Route::get('/agents', [AgentsController::class, 'index'])->name('agents.index');
Route::get('/agents/{agent}/history', [AgentsController::class, 'history'])->name('agents.history');
Route::post('/agents/{agent}/tasks', [AgentsController::class, 'addTask'])->name('agents.addTask');
/*
|--------------------------------------------------------------------------
| DevAgent Managed Routes
| Only DevAgent modifies the lines between START/END markers.
| Cleanup will rebuild this block without touching your core routes above.
|--------------------------------------------------------------------------
*/
// >>> DEVAGENT:ROUTES:START
// (auto-generated by DevAgent)
// >>> DEVAGENT:ROUTES:END
Route::post('/agents/cleanup-routes', [AgentsController::class, 'cleanupRoutes'])->name('agents.cleanupRoutes');

Route::get('/agents/summaries', [App\Http\Controllers\AgentsController::class, 'summaries'])->name('agents.summaries');
Route::get('/agents/summaries/{filename}', [App\Http\Controllers\AgentsController::class, 'viewSummary'])->name('agents.viewSummary');

Route::get('/docs', [App\Http\Controllers\DocsController::class, 'index'])->name('docs.index');
Route::get('/docs/view/{filename}', [App\Http\Controllers\DocsController::class, 'view'])->name('docs.view');
