<?php
// agents/DevAgent.php
/**
 * Tasks supported:
 *  - "Scaffold controller {Name}Controller"
 *  - "cleanup routes"
 */

$task = $argv[1] ?? null;
if (!$task) {
    echo "❌ No task provided.\n";
    exit(1);
}

function logTask($agent, $status, $task) {
    $logFile = __DIR__ . '/../logs/agent-log.jsonl';
    $entry = [
        'time'   => date('Y-m-d H:i:s'),
        'agent'  => $agent,
        'status' => $status,
        'task'   => $task,
        'source' => 'DevAgent',
    ];
    file_put_contents($logFile, json_encode($entry) . PHP_EOL, FILE_APPEND);
}

logTask('DevAgent', 'in-progress', $task);

try {
    $basePath     = __DIR__ . '/../ai-agent-dashboard';
    $controllers  = "{$basePath}/app/Http/Controllers";
    $routesPath   = "{$basePath}/routes/web.php";

    if (!is_dir($controllers)) {
        throw new Exception("Controllers path not found: {$controllers}");
    }
    if (!file_exists($routesPath)) {
        throw new Exception("Routes file missing: {$routesPath}");
    }

    // --- helpers for the managed block ---
    $START = '// >>> DEVAGENT:ROUTES:START';
    $END   = '// >>> DEVAGENT:ROUTES:END';

    $readRoutes = function () use ($routesPath) {
        return file($routesPath, FILE_IGNORE_NEW_LINES);
    };

    $writeRoutes = function (array $lines) use ($routesPath) {
        file_put_contents($routesPath, implode(PHP_EOL, $lines) . PHP_EOL);
    };

    $ensureBlock = function (array $lines) use ($START, $END) {
        $hasStart = false; $hasEnd = false;
        foreach ($lines as $ln) {
            if (trim($ln) === $START) $hasStart = true;
            if (trim($ln) === $END)   $hasEnd   = true;
        }
        if ($hasStart && $hasEnd) return $lines;

        // Append empty block at end if missing
        $lines[] = '';
        $lines[] = $START;
        $lines[] = '// (auto-generated by DevAgent)';
        $lines[] = $END;
        return $lines;
    };

    $extractBlock = function (array $lines) use ($START, $END) {
        $before = []; $block = []; $after = [];
        $in = 'before';
        foreach ($lines as $ln) {
            if (trim($ln) === $START) { $in = 'block'; $block[] = $ln; continue; }
            if (trim($ln) === $END)   { $block[] = $ln; $in = 'after'; continue; }

            if ($in === 'before') $before[] = $ln;
            elseif ($in === 'block') $block[] = $ln;
            else $after[] = $ln;
        }
        return [$before, $block, $after];
    };

    $rebuildBlock = function (array $controllersToKeep) use ($START, $END) {
        $new = [];
        $new[] = $START;
        $new[] = '// (auto-generated by DevAgent)';
        foreach ($controllersToKeep as $ctrl) {
            $new[] = "use App\\Http\\Controllers\\{$ctrl};";
            $new[] = "Route::get('/test-{$ctrl}', [{$ctrl}::class, 'index']);";
        }
        $new[] = $END;
        return $new;
    };

    // --- CLEANUP MODE ---
    if (preg_match('/^cleanup routes$/i', $task)) {
        $lines = $readRoutes();
        $lines = $ensureBlock($lines);
        [$before, $block, $after] = $extractBlock($lines);

        // scan current block for controllers, keep only those with existing files
        $existing = [];
        foreach ($block as $ln) {
            if (preg_match('/use\s+App\\\\Http\\\\Controllers\\\\([A-Za-z0-9_]+);/', $ln, $m)) {
                $ctrl = $m[1];
                $ctrlFile = "{$controllers}/{$ctrl}.php";
                if (file_exists($ctrlFile)) {
                    $existing[] = $ctrl;
                } else {
                    echo "🧹 Removing stale entries for: {$ctrl}\n";
                }
            }
        }

        $newBlock = $rebuildBlock(array_unique($existing));
        $writeRoutes(array_merge($before, $newBlock, $after));

        echo "✅ Cleanup complete.\n";
        logTask('DevAgent', 'completed', "Routes cleaned");
        exit(0);
    }

    // --- SCAFFOLD CONTROLLER ---
    if (preg_match('/scaffold controller (.+)/i', $task, $matches)) {
        $name = trim($matches[1]);
        // normalize name to end with "Controller"
        if (!preg_match('/Controller$/', $name)) {
            $name .= 'Controller';
        }

        $ctrlFile = "{$controllers}/{$name}.php";

        // create controller if missing
        if (!file_exists($ctrlFile)) {
            $template = <<<PHP
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class {$name} extends Controller
{
    public function index()
    {
        return response()->json(['message' => '{$name} index works!']);
    }
}
PHP;
            file_put_contents($ctrlFile, $template);
            echo "✅ Controller scaffolded: {$name}\n";
        } else {
            echo "⚠️ Controller already exists: {$name}\n";
        }

        // add route inside managed block (dedup)
        $lines = $readRoutes();
        $lines = $ensureBlock($lines);
        [$before, $block, $after] = $extractBlock($lines);

        $useLine   = "use App\\Http\\Controllers\\{$name};";
        $routeLine = "Route::get('/test-{$name}', [{$name}::class, 'index']);";

        $hasUse = false; $hasRoute = false;
        foreach ($block as $ln) {
            if (trim($ln) === trim($useLine))   $hasUse = true;
            if (trim($ln) === trim($routeLine)) $hasRoute = true;
        }

        // Build final set of controllers in block
        $controllersInBlock = [];
        foreach ($block as $ln) {
            if (preg_match('/use\s+App\\\\Http\\\\Controllers\\\\([A-Za-z0-9_]+);/', $ln, $m)) {
                $controllersInBlock[] = $m[1];
            }
        }
        if (!in_array($name, $controllersInBlock, true)) {
            $controllersInBlock[] = $name;
        }

        $newBlock = $rebuildBlock(array_unique($controllersInBlock));
        $writeRoutes(array_merge($before, $newBlock, $after));

        if (!$hasUse || !$hasRoute) {
            echo "✅ Test route ensured: /test-{$name}\n";
        } else {
            echo "⚠️ Test route already present: /test-{$name}\n";
        }

        logTask('DevAgent', 'completed', "Scaffolded controller + route for {$name}");
        exit(0);
    }

    // Unknown task
    logTask('DevAgent', 'failed', "Unknown task: {$task}");
    echo "❌ Unknown task format.\n";
    exit(1);

} catch (Exception $e) {
    logTask('DevAgent', 'failed', "Error: " . $e->getMessage());
    echo "❌ Exception: " . $e->getMessage() . "\n";
    exit(1);
}
